global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'myapp'
    static_configs:
      -targets: ['cadvisor:9090']

  - job_name: 'cadvisor'
    static_configs:
      -targets: ['cadvisor:8080']